services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .production.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5000:5000
      - 9229:9229
    command: npm run start:prod
    restart: always
